security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ouyang_test
    username: root
    password: ouyang
  jpa:
    database: mysql
    show-sql: true
#  data:
#    mongodb:
#      host: account-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: ouyang
#      port: 27017

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true