spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysqlaa
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
#  data:
#    mongodb:
#      host: auth-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
#      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
